version: "3.8"
services:
  e_clients:
    build:
      context: ./e_clients
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8800
    depends_on:
      - e_server
    networks:
      - app-network

  e_server:
    build:
      context: ./e_server
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
